triggers:
- description: null
  envs: []
  last_enabled_at: 2026-02-09 12:20:03.176975+00:00
  name: check_on_start
  pipeline_uuid: push_private_keys
  schedule_interval: '@once'
  schedule_type: time
  settings:
    create_initial_pipeline_run: true
  sla: null
  start_time: 2026-02-09 12:18:00+00:00
  status: active
  token: b43a25ea5a224f75b766048ecd2075a5
  variables: {}
